// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/helloworld.proto

package io.assalielmehdi.helloworld.grpc;

public interface HelloWorldRequestOrBuilder extends
  // @@protoc_insertion_point(interface_extends:helloworld.HelloWorldRequest)
  com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberOfMessages = 1;</code>
   *
   * @return The numberOfMessages.
   */
  int getNumberOfMessages();
}
