// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/helloworld.proto

package io.assalielmehdi.helloworld.grpc;

public final class HelloWorldProto {
  private HelloWorldProto() {
  }

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
      (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloWorldRequest_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_helloworld_HelloWorldRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_HelloWorldResponse_descriptor;
  static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internal_static_helloworld_HelloWorldResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
    descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\033main/proto/helloworld.proto\022\nhelloworl" +
        "d\"-\n\021HelloWorldRequest\022\030\n\020numberOfMessag" +
        "es\030\001 \001(\005\"&\n\022HelloWorldResponse\022\020\n\010messag" +
        "es\030\001 \003(\t2^\n\nHelloWorld\022P\n\rsayHelloWorld\022" +
        "\035.helloworld.HelloWorldRequest\032\036.hellowo" +
        "rld.HelloWorldResponse\"\000B5\n io.assalielm" +
        "ehdi.helloworld.grpcB\017HelloWorldProtoP\001b" +
        "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[]{
        });
    internal_static_helloworld_HelloWorldRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_HelloWorldRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
      internal_static_helloworld_HelloWorldRequest_descriptor,
      new java.lang.String[]{"NumberOfMessages",});
    internal_static_helloworld_HelloWorldResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_HelloWorldResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
      internal_static_helloworld_HelloWorldResponse_descriptor,
      new java.lang.String[]{"Messages",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
